/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.book;

import business.AirlinerDirectory;
import business.FlightDirectory;
import business.Users.User;
import dataitems.Airliner;
import dataitems.Flight;
import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.HashSet;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author riverlin
 */
public class CustomerBookJPanel extends javax.swing.JPanel {

    private JPanel panelRight;
    private User u1;
    private Airliner currentAirliner;
    private AirlinerDirectory airlinerlist;

    /**
     * Creates new form CustomerBookJPanel
     */
    public CustomerBookJPanel(JPanel panelRight, AirlinerDirectory airlinerlist, User u) {
        initComponents();
        jLabel2.setText(u.getName() + jLabel2.getText());
        this.airlinerlist = airlinerlist;
        this.panelRight = panelRight;
        u1 = u;
        this.populateInitTable();
    }

    public void populateInitTable() {

        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        dtm.setRowCount(0);

//        ArrayList<String>  flightlist = new ArrayList<>();
//        ArrayList<String>  airlinerlist = new ArrayList<>();
//        ArrayList<String>  datelist = new ArrayList<>();
//        ArrayList<String>  airplanelist = new ArrayList<>();
//        ArrayList<String>  routelist = new ArrayList<>();
//        int i = 0;
        for (Airliner airliner : airlinerlist.getAirlinerlist()) {
            for (Flight flight : airliner.getFlightDirectory().getFlightlist()) {
                Object[] row = new Object[5];
                row[0] = flight;
                row[1] = flight.getAirliner();
                row[2] = flight.getDate();
                row[3] = flight.getAirplane();
                row[4] = flight.getRoute();

                jComboBox1.addItem(flight.getFlight());
                jComboBox6.addItem(flight.getAirliner());
                jComboBox7.addItem(flight.getDate());
                jComboBox8.addItem(flight.getAirplane());
                jComboBox9.addItem(flight.getRoute());

                dtm.addRow(row);

            }
        }
    }
    
    public void populate() {

        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        dtm.setRowCount(0);

//        ArrayList<String>  flightlist = new ArrayList<>();
//        ArrayList<String>  airlinerlist = new ArrayList<>();
//        ArrayList<String>  datelist = new ArrayList<>();
//        ArrayList<String>  airplanelist = new ArrayList<>();
//        ArrayList<String>  routelist = new ArrayList<>();
//        int i = 0;
        for (Airliner airliner : airlinerlist.getAirlinerlist()) {
            for (Flight flight : airliner.getFlightDirectory().getFlightlist()) {
                Object[] row = new Object[5];
                row[0] = flight;
                row[1] = flight.getAirliner();
                row[2] = flight.getDate();
                row[3] = flight.getAirplane();
                row[4] = flight.getRoute();

                

                dtm.addRow(row);

            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        searchbtn = new javax.swing.JButton();
        bookbtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox6 = new javax.swing.JComboBox<>();
        jComboBox7 = new javax.swing.JComboBox<>();
        jComboBox8 = new javax.swing.JComboBox<>();
        jComboBox9 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Flight", "Airliner", "Date", "Airplane", "Route"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel1.setText("Book Flight");

        searchbtn.setBackground(new java.awt.Color(102, 153, 255));
        searchbtn.setText("Search");
        searchbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbtnActionPerformed(evt);
            }
        });

        bookbtn.setText("Book");
        bookbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookbtnActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(0, 153, 204));
        jLabel2.setText(" is booking :");

        jButton1.setText("Clean Research");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(342, 342, 342)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 599, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(jComboBox7, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox8, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(jComboBox9, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(searchbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(bookbtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(91, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(searchbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bookbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(101, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void searchbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbtnActionPerformed
        // TODO add your handling code here:
        String s1 = (String) this.jComboBox1.getSelectedItem();
        String s2 = (String) this.jComboBox6.getSelectedItem();
        String s3 = (String) this.jComboBox7.getSelectedItem();
        String s4 = (String) this.jComboBox8.getSelectedItem();
        String s5 = (String) this.jComboBox9.getSelectedItem();

        FlightDirectory tempFlights = new FlightDirectory();

        for (Airliner airliner : airlinerlist.getAirlinerlist()) {
            for (Flight flight : airliner.getFlightDirectory().getFlightlist()) {
                int score = 0;
                if (flight.getFlight().equals(s1)) {
                    score++;
                }
                if (flight.getAirliner().equals(s2)) {
                    score++;
                }
                if (flight.getDate().equals(s3)) {
                    score++;
                }
                if (flight.getAirplane().equals(s4)) {
                    score++;
                }
                if (flight.getRoute().equals(s5)) {
                    score++;
                }
                if (score == 5) {
                    tempFlights.getFlightlist().add(flight);
                }
            }
        }
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        dtm.setRowCount(0);
        for (Flight flight : tempFlights.getFlightlist()) {
            Object[] row = new Object[5];
            row[0] = flight;
            row[1] = flight.getAirliner();
            row[2] = flight.getDate();
            row[3] = flight.getAirplane();
            row[4] = flight.getRoute();

            dtm.addRow(row);

        }

//        if (s1 != "all") {
//            for (Flight flight : flightlist) {
//                if (account.getRoutingnumber().equals(smn)) {
//                    temphistory.addAccount(account);
//                }
//                return temphistory;
//                Flight result1 = ;
//                if (result2 == null) {
//                    JOptionPane.showMessageDialog(null, "Car does not exist", "Information", JOptionPane.INFORMATION_MESSAGE);
//                } else {
//
//                    tempHistory = result2;
//                }
//            }

    }//GEN-LAST:event_searchbtnActionPerformed

    private void bookbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookbtnActionPerformed
        // TODO add your handling code here:
        int selectedrow = jTable1.getSelectedRow();
        if (selectedrow < 0){
            JOptionPane.showMessageDialog(null,"Please select any row to view details","warning",JOptionPane.WARNING_MESSAGE);
        }
        else{
            Flight f1 = (Flight)jTable1.getValueAt(selectedrow, 0);
            CustomerSeatJPanel mm = new CustomerSeatJPanel(this.panelRight, f1,u1);
            CardLayout layout = (CardLayout) panelRight.getLayout();
            panelRight.add(mm);
            layout.next(panelRight);
                  
            
        }
        
    }//GEN-LAST:event_bookbtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jComboBox1.setSelectedIndex(0);
        jComboBox6.setSelectedIndex(0);
        jComboBox7.setSelectedIndex(0);
        jComboBox8.setSelectedIndex(0);
        jComboBox9.setSelectedIndex(0);
        populate();
        
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bookbtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JComboBox<String> jComboBox7;
    private javax.swing.JComboBox<String> jComboBox8;
    private javax.swing.JComboBox<String> jComboBox9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton searchbtn;
    // End of variables declaration//GEN-END:variables
}
