/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.managetravelagency;

import business.FlightDirectory;
import business.TicketDirectory;
import business.UserDirectory;
import business.Users.Customer;
import dataitems.Flight;
import dataitems.Ticket;
import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.HashSet;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author riverlin
 */
public class CustomerManageJPanel extends javax.swing.JPanel {
    private JPanel panelRight;
    private TicketDirectory ticketdirectory;
    DefaultTableModel dtm;
    ArrayList<Customer>cl;
    
    public TicketDirectory getTicketDirectory(){
        return this.ticketdirectory;
    }

    /**
     * Creates new form CustomerManageJPanel
     */
    public CustomerManageJPanel(JPanel panelRight,ArrayList<Customer>customerlist) {
        initComponents();
        this.panelRight=panelRight;
        this.ticketdirectory=ticketdirectory;
        this.cl=customerlist;
        populateInitTable(ticketdirectory);
    }
    
    
    private void populateInitTable(TicketDirectory ticketdirectory){
        
        //cbbrand.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"all"}));
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        dtm.setRowCount(0);
        HashSet set = new HashSet();
       
//        ArrayList<String>  brandlist = new ArrayList<>();
//        ArrayList<String>  citylist = new ArrayList<>();
//        ArrayList<String>  mylist = new ArrayList<>();
//        ArrayList<String>  usedlist = new ArrayList<>();
//        ArrayList<String>  cetilist = new ArrayList<>();
        
        for(Customer customer : cl){
            
        if (!set.contains(customer.getName())){
                int j = 0;
                jComboBox1.addItem(customer.getName());
        
            for(Ticket ticket : customer.getticketdirectory().getTicketlist()){
            Object [] row = new Object [3];
            String i = null;
            
            row[0] = ticket.getFlight();
            row[1] = ticket.getX();
            if(ticket.getY()==0){
                i= "A";
            }if(ticket.getY()==1){
                i= "B";
            }if(ticket.getY()==2){
                i= "C";
            }if(ticket.getY()==3){
                i= "D";
            }if(ticket.getY()==4){
                i= "E";
            }if(ticket.getY()==5){
                i= "F";
            }
            row[2] = i;
            
            
            dtm.addRow(row);
        
        }
                
            }
        }
        
        
    }
    
    
    private void populateTable(TicketDirectory ticketdirectory){
        //cbbrand.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"all"}));
       
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        dtm.setRowCount(0);
        HashSet set = new HashSet();
       
        
        
        
        for(Ticket ticket : ticketdirectory.getTicketlist()){
            Object [] row = new Object [3];
            String i = null;
            
            row[0] = ticket.getFlight();
            row[1] = ticket.getX();
            if(ticket.getY()==0){
                i= "A";
            }if(ticket.getY()==1){
                i= "B";
            }if(ticket.getY()==2){
                i= "C";
            }if(ticket.getY()==3){
                i= "D";
            }if(ticket.getY()==4){
                i= "E";
            }if(ticket.getY()==5){
                i= "F";
            }
            row[2] = i;
            dtm.addRow(row);
        
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Flight", "Row", "Columns"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Delete Tickets");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel1.setText("Customer Name :");

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel2.setText("Tickets Manage");

        jButton2.setText("< Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(321, 321, 321))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addGap(18, 18, 18)
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 588, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 426, Short.MAX_VALUE)
                                .addComponent(jButton1)))
                        .addGap(59, 59, 59))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel2)
                .addGap(97, 97, 97)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(145, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int selectedrow = jTable1.getSelectedRow();
        if(selectedrow >= 0 )
        {
            int dialogButton = JOptionPane.YES_NO_OPTION;
            int dialogResult = JOptionPane.showConfirmDialog(null,"Would you like to delete this ticket?","warning", dialogButton);
            if(dialogResult== JOptionPane.YES_NO_OPTION){
                Ticket ticket = (Ticket) jTable1.getValueAt(selectedrow, 0);
                ticketdirectory.deleteTicket(ticket.getFlight(),ticket.getX(),ticket.getY());
                populateTable(ticketdirectory);
            }
            
                    
                    
           
                    }
        else
            JOptionPane.showMessageDialog(null,"Please select any ticket !","warning",JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        panelRight.remove(this);
        CardLayout layout = (CardLayout)panelRight.getLayout();
        layout.previous(panelRight);
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
